# Generated by Django 2.2.19 on 2023-06-07 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование продукта')),
                ('purchase_price_per_unit', models.IntegerField(verbose_name='Цена закупки за штуку')),
                ('available_quantity', models.IntegerField(verbose_name='Количество на складе')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование поставщика')),
                ('number', models.CharField(max_length=16, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование работы')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_w', to='workzone.Work', verbose_name='Работа')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_w', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Умение работника в определённой работе',
                'verbose_name_plural': 'Умения работников в определённой работе',
            },
        ),
        migrations.CreateModel(
            name='WorkProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='workzone.Product', verbose_name='Продукт')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_p', to='workzone.Work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Необходимый продукт для выполнения работы',
                'verbose_name_plural': 'Необходимые продукт для выполнения работы',
            },
        ),
        migrations.CreateModel(
            name='WorkInProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование продукта')),
                ('ready_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_in_process', to='workzone.Product')),
                ('work_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_in_process', to='workzone.Work')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_in_process', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Работа в процессе',
                'verbose_name_plural': 'Работы в процессе',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='workzone.Provider', verbose_name='Поставщик'),
        ),
        migrations.AddConstraint(
            model_name='workworker',
            constraint=models.UniqueConstraint(fields=('work', 'worker'), name='uq_work_worker'),
        ),
        migrations.AddConstraint(
            model_name='workproduct',
            constraint=models.UniqueConstraint(fields=('work', 'product'), name='uq_work_product'),
        ),
    ]
