# Generated by Django 2.2.19 on 2023-06-13 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_auto_20230608_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование продукта')),
                ('purchase_price_per_unit', models.IntegerField(verbose_name='Цена закупки за штуку')),
                ('available_quantity', models.IntegerField(verbose_name='Количество на складе')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование поставщика')),
                ('number', models.CharField(max_length=16, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkInProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='works_in_process', to='shop.Type')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works_in_process', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Работа в процессе',
                'verbose_name_plural': 'Работы в процессе',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_t', to='workzone.Product', verbose_name='Продукт')),
                ('type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='type_p', to='shop.Type', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Необходимый продукт для выполнения работы',
                'verbose_name_plural': 'Необходимые продукт для выполнения работы',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='workzone.Provider', verbose_name='Поставщик'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(verbose_name='Размер')),
                ('mail_index', models.CharField(max_length=12, verbose_name='Почтовый индекс')),
                ('client_fullname', models.CharField(max_length=6, verbose_name='ФИО клиента')),
                ('client_number', models.CharField(max_length=24, verbose_name='Номер клиента')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('ready_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shop.ReadyProduct', verbose_name='Готовый продукт')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='typeproduct',
            constraint=models.UniqueConstraint(fields=('type', 'product'), name='uq_type_product'),
        ),
    ]
