# Generated by Django 2.2.19 on 2023-06-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workzone', '0004_auto_20230613_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='provider_id',
            new_name='provider',
        ),
    ]
