# Generated by Django 2.2.19 on 2023-06-15 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workzone', '0006_auto_20230614_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeproduct',
            options={'ordering': ['type'], 'verbose_name': 'Необходимый продукт для выполнения работы', 'verbose_name_plural': 'Необходимые продукты для выполнения работы'},
        ),
        migrations.AddField(
            model_name='order',
            name='client_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_type', to='shop.Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='worker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_worker', to=settings.AUTH_USER_MODEL),
        ),
    ]
