# Generated by Django 2.2.19 on 2023-06-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workzone', '0008_auto_20230615_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client_id',
            new_name='client',
        ),
    ]
