# Generated by Django 2.2.19 on 2023-06-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименовение продукта')),
                ('selling_price_per_unit', models.IntegerField(verbose_name='Цена продажи за штуку')),
                ('available_quantity', models.IntegerField(verbose_name='Количество на складе')),
            ],
            options={
                'verbose_name': 'Готовый продукт',
                'verbose_name_plural': 'Готовые продукты',
                'ordering': ['id'],
            },
        ),
    ]
