# Generated by Django 2.2.19 on 2023-06-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readyproduct',
            name='picture_name',
            field=models.ImageField(default=None, upload_to='shoes/'),
        ),
    ]
