# Generated by Django 2.2.19 on 2023-06-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_readyproduct_picture_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readyproduct',
            old_name='picture_name',
            new_name='picture',
        ),
    ]
