# Generated by Django 2.2.19 on 2023-06-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230608_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='readyproduct',
            name='model',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='Модель продукта'),
        ),
    ]
