# Generated by Django 2.2.19 on 2023-06-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_readyproduct_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readyproduct',
            name='model',
            field=models.CharField(max_length=64, verbose_name='Модель продукта'),
        ),
    ]
