# Generated by Django 2.2.19 on 2023-06-08 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20230608_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='readyproduct',
            name='name',
        ),
        migrations.AddField(
            model_name='readyproduct',
            name='collection',
            field=models.CharField(default='-ytn-', max_length=64, verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='readyproduct',
            name='color',
            field=models.CharField(max_length=64, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='readyproduct',
            name='description',
            field=models.CharField(max_length=640, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='readyproduct',
            name='type',
            field=models.ForeignKey(blank=True, max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Type', verbose_name='Тип'),
        ),
    ]
