# Generated by Django 2.2.19 on 2023-05-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=64, verbose_name='Работник')),
                ('number', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('password', models.CharField(default='123456', max_length=16, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
                'ordering': ['id'],
            },
        ),
    ]
