# Generated by Django 2.2.19 on 2023-03-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worker',
            new_name='Workers',
        ),
    ]
