# Generated by Django 2.2.19 on 2023-05-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=64, verbose_name='Покупатель')),
                ('number', models.CharField(max_length=32, verbose_name='Почта')),
                ('password', models.CharField(default='123456', max_length=16, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ['id'],
            },
        ),
    ]
