# Generated by Django 2.2.19 on 2023-05-29 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='number',
            new_name='email',
        ),
    ]
