# Generated by Django 2.2.19 on 2023-06-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230607_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(default=753986, verbose_name='Код подтверждения'),
        ),
    ]
