# Generated by Django 2.2.19 on 2023-03-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230303_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['id'], 'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AddField(
            model_name='worker',
            name='password',
            field=models.CharField(default='123456', max_length=16, verbose_name='Пароль'),
        ),
    ]
