# Generated by Django 2.2.19 on 2023-06-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230608_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(default=136440, verbose_name='Код подтверждения'),
        ),
    ]
