# Generated by Django 2.2.19 on 2023-05-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230529_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmed_code',
            field=models.IntegerField(max_length=32, verbose_name='Код подтверждения'),
        ),
    ]
