# Generated by Django 2.2.19 on 2023-06-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230608_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(default=569825, verbose_name='Код подтверждения'),
        ),
    ]
