# Generated by Django 2.2.19 on 2023-05-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230529_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmed_code',
            field=models.IntegerField(verbose_name='Код подтверждения'),
        ),
    ]
