# Generated by Django 2.2.19 on 2023-05-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230529_0611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirmed_code',
            new_name='confirm_code',
        ),
    ]
