# Generated by Django 2.2.19 on 2023-05-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230529_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name_surname',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
