# Generated by Django 2.2.19 on 2023-06-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20230608_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(default=881070, verbose_name='Код подтверждения'),
        ),
    ]
