# Generated by Django 2.2.19 on 2023-06-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20230608_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_orders',
            field=models.IntegerField(default=0, verbose_name='Активные заказы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(default=655848, verbose_name='Код подтверждения'),
        ),
    ]
