# Generated by Django 2.2.19 on 2023-06-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20230613_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(default=844167, verbose_name='Код подтверждения'),
        ),
    ]
