# Generated by Django 2.2.19 on 2023-06-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20230613_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(default=584272, verbose_name='Код подтверждения'),
        ),
    ]
