# Generated by Django 2.2.19 on 2023-06-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20230613_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(default=387595, verbose_name='Код подтверждения'),
        ),
    ]
