# Generated by Django 2.2.19 on 2023-06-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20230613_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(default=997193, verbose_name='Код подтверждения'),
        ),
    ]
