# Generated by Django 2.2.19 on 2023-06-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20230613_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(default=921521, verbose_name='Код подтверждения'),
        ),
    ]
