# Generated by Django 2.2.19 on 2023-06-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20230613_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(default=803141, verbose_name='Код подтверждения'),
        ),
    ]
