# Generated by Django 2.2.19 on 2023-06-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20230613_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(default=561629, verbose_name='Код подтверждения'),
        ),
    ]
