# Generated by Django 2.2.19 on 2023-06-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20230613_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(default=536763, verbose_name='Код подтверждения'),
        ),
    ]
