# Generated by Django 2.2.19 on 2023-06-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20230613_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(default=831601, verbose_name='Код подтверждения'),
        ),
    ]
