# Generated by Django 2.2.19 on 2023-06-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20230613_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(default=851632, verbose_name='Код подтверждения'),
        ),
    ]
