# Generated by Django 2.2.19 on 2023-06-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20230613_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(default=259112, verbose_name='Код подтверждения'),
        ),
    ]
