# Generated by Django 2.2.19 on 2023-06-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20230613_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(default=434145, verbose_name='Код подтверждения'),
        ),
    ]
