# Generated by Django 2.2.19 on 2023-06-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20230614_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(default=951140, verbose_name='Код подтверждения'),
        ),
    ]
